eureka:
  instance:
     preferIpAddress: true
  client:
    serviceUrl:
       defaultZone: http://microservices-refapp-eureka-chrisking.mybluemix.net/eureka/


# Spring properties
spring:
  application:
     name: socialreview-microservice


# Server configuration
server:
  context-path: /micro
  port: 8080


# Cloudant Confiugration
cloudant:
  username:
  password:
  host:
